<?php

return [
    'Visualizar Usuários',
    'Criar Usuários',
    'Editar Usuários',
    'Excluir Usuários',
    'Visualizar Todos os Usuários',
    'Editar Todos os Usuários',
    'Excluir Todos os Usuários',

    'Visualizar Categorias',
    'Criar Categorias',
    'Editar Categorias',
    'Excluir Categorias',
    'Visualizar Todas as Categorias',
    'Editar Todas as Categorias',
    'Excluir Todas as Categorias',

    'Visualizar Tags',
    'Criar Tags',
    'Editar Tags',
    'Excluir Tags',
    'Visualizar Todas as Tags',
    'Editar Todas as Tags',
    'Excluir Todas as Tags',

    'Visualizar Posts',
    'Criar Posts',
    'Editar Posts',
    'Excluir Posts',
    'Visualizar Todos os Posts',
    'Editar Todos os Posts',
    'Excluir Todos os Posts',

    'Visualizar Arquivos',
    'Criar Arquivos',
    'Editar Arquivos',
    'Excluir Arquivos',
    'Visualizar Todos os Arquivos',
    'Editar Todos os Arquivos',
    'Excluir Todos os Arquivos',
    
    'Visualizar Clientes',
    'Cadastrar Clientes',
    'Editar Clientes',
    'Excluir Clientes',
    'Visualizar Todos os Clientes',
    'Editar Todos os Clientes',
    'Excluir Todos os Clientes',
    
    'Visualizar Portfolios',
    'Cadastrar Portfolios',
    'Editar Portfolios',
    'Excluir Portfolios',
    'Visualizar Todos os Portfolios',
    'Editar Todos os Portfolios',
    'Excluir Todos os Portfolios',
    
    'Visualizar Equipes',
    'Cadastrar Equipes',
    'Editar Equipes',
    'Excluir Equipes',
    'Visualizar Todas as Equipes',
    'Editar Todas as Equipes',
    'Excluir Todas as Equipes',
];
